#!/bin/bash

<<comment
"
This Sub-domain enumeration script includes these tools
1. Sub-finder
2. assetfinder
3. findomain
4. crtsh
5. Chaos
"
comment


# Check if the user provided a filename argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 <filename>"
    exit 1
elif [ ! -f "$1" ]; then
    echo "File '$1' does not exist."
    exit 1
fi

file_path="$PWD/$1"

#Sub-finder
subfinder -dL "$file_path" -silent -all -recursive | anew subs.txt;

#assetfinder
cat "$file_path" | assetfinder -subs-only | anew subs.txt;

#findomain
findomain  -f alive.txt | grep -oE '([a-zA-Z0-9]+\.){1,}[a-zA-Z]{2,}' | anew subs.txt;

#crtsh
cat $file_path | while read url; do crtsh -d $url | anew subs.txt; done

# anew subs.txt && chaos -dL wildcards.txt | anew subs.txt && sublist3r -dL wildcards.txt | grep -oE '([a-zA-Z0-9]+\.){1,}[a-zA-Z]{2,}' | anew subs.txt && assetfinder -subs-only wildcards.txt | anew subs.txt && findomain -t wildcards.txt | anew subs.txt && cat subs.txt | uniq | sort -uR | anew subs.filtered && httpx -l subs.filtered -threads 200 -follow-redirects -silent -random-agent -ports 80,443,8009,8080,8081,8090,8180,8443,5000,7000,8082,3000 -mc 200 -o alive.txt && rm -r subs.filtered subs.txt

